### ISSUE TITLE
Fix skeleton loading on refetch interval

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer#18]
Actually for the lists that have a refetch interval de skeleton isLoading is shown every refetch interval. 

Use isFetched or similar instead and show a loader only at first fetch.

![image](https://github.com/vocdoni/explorer/assets/16777076/72e4f252-4c99-4b6a-af4e-4f2fa0431df7)

i.e. https://github.com/vocdoni/vote-frame/blob/main/webapp/src/pages/communities/mine.tsx#L24

**Comment by elboletaire** [comment]
In the end we want the lists of items, like the blocks in the landing page, to not load the skeleton on re-fetches, which is its current behavior.

![imatge](https://github.com/vocdoni/explorer/assets/153305/28e8c297-7590-4082-b5ce-c9a64572a7ca)
