### ISSUE TITLE
Filtering by paused fails to load

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/explorer#24]
see https://vocdoni-explorer-dev.netlify.app/processes?status=PAUSED

or https://vocdoni-explorer-stg.netlify.app/processes?status=PAUSED

**Comment by selankon** [comment]
Not sure is an error of the explorer. The API returns 404

**Comment by elboletaire** [comment]
> Not sure is an error of the explorer. The API returns 404

Agree, but we should improve its handling... reduce the attempts if it returns certain errors, and maybe ensure we show the error sooner

**Comment by selankon** [comment]
I guess the number of attempts is managed by the SDK. I can research a bit more. Also show a loader when is searching by filters.

**Comment by elboletaire** [comment]
> I guess the number of attempts is managed by the SDK. I can research a bit more. Also show a loader when is searching by filters.

react-query by default retries up to 5 times if I'm not wrong if the query throws an error. But the retries and stuff are handled by react query itself.

**Comment by elboletaire** [comment]
Closed by #42
