### ISSUE TITLE
Search by blocks does not seem to work

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/explorer#28]
Steps to reproduce:
- Go to the blocks list https://vocdoni-explorer-stg.netlify.app/blocks
- Add a number into the search field, i.e. `560`
- Notice the URL changed to some weird block number (it set 109610 for me)
- There's no response at all, returning a 404

**Comment by selankon** [comment]
`109610` Is not a weird number, is the page number (if there are, i don't know 1118856, the page where to find the block 560 is the page `111830`). There are 1118856 /10 = 111885'6 pages, so the number has sense.

The thing is that the API is returning 404 for old blocks. If you search new ones the pagination works well.

In any case, this is bad UX, somehow related to #40

**Comment by elboletaire** [comment]
But the page should be zero/one when searching for the first time, not the last page (?)

**Comment by elboletaire** [comment]
Ok so we have at least two things here:

- Only new blocks and transactions are indexed so, in stg environment, most blocks and transactions do not exist, since it was reset not long ago, recovering the chain from a certain block height (making all old blocks inaccessible)
- The search/find behavior needs a UX revamp to differentiate the filtering in organizations and elections, with the "go to" behavior we have in blocks and transactions. This last one should be changed from an input to a button showing a prompt (or inline input) that says "go to", rather than "search".

**Comment by selankon** [comment]
The go to will be implemented on  https://github.com/vocdoni/explorer/pull/42 and its related to https://github.com/vocdoni/explorer/issues/40

**Comment by elboletaire** [comment]
Closed by #42
