### ISSUE TITLE
Search process by organization id

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer#41]
Actually is disabled because doesn't work very well. Check how to make it working

https://github.com/vocdoni/explorer/blob/14e9aee1c5478d0254c02484a248d987eccf159d/src/components/Process/ProcessList.tsx#L105

**Comment by elboletaire** [comment]
I think you'll need to check the length and/or format of the inserted value (i.e. addresses have 42 chars)

**Comment by selankon** [comment]
This is issue is not an issue at all.

The deterministic processId already contains the organization id, for example: 

Inside this process 

https://dev.explorer.vote/process/6be21a5a9dc0170a9773d14ea10a3ed90699b88cf9dafab9952e020200000000

You can see the orgId that created the process `170a9773d14ea10a3ed90699b88cf9dafab9952e`:

https://dev.explorer.vote/organization/170a9773d14ea10a3ed90699b88cf9dafab9952e

Searching by partial processId is already working so this is not needed to be implemented, you can search by partial org id at the same time as by partial processId (which actually is not a very important use case, but, whatever... )

**Comment by selankon** [comment]
I will add a odd length checker to improve the search box
