### ISSUE TITLE
Explorer v2 - Next steps

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/explorer#65]
Use this issue to add links to endpoints or documentation of stuff that could be useful in the explorer but is not yet implemented.

- [x] Rename Organizations to Accounts <- Last one to avoid merge conflicts with other ones
- [x] On the account details:
     - [x] Total number of transactions sent from the [API endpoint](https://developer.vocdoni.io/vocdoni-api/total-number-of-sent-and-received-transactions)
     - [x] Show the current token balance (available in the /account/:address endpoint)
     - [x] List the last sent/received TOKEN transfers from `/accounts/:accountID/transfers/page/:page`
     - [x] List the last executed transactions and its associated fee from `/accounts/:accountID/fees/page/:page`, more here  [Token fees issue](https://github.com/vocdoni/interoperability/issues/84)
- [x] [List account transfers](https://developer.vocdoni.io/vocdoni-api/list-account-received-and-sent-token-transfers)
- [x] #76 . 
- [x] #77
- [x] https://github.com/vocdoni/explorer/issues/88
- [x] https://github.com/vocdoni/explorer/issues/90
- [x] https://github.com/vocdoni/explorer/issues/91
- [x] https://github.com/vocdoni/explorer/issues/93
- [x] Do translations
- [x] ~~On transactions details, show only the RAW content of `tx` and `signature`, not `txInfo`. Since txInfo is already shown in Details tab. Maybe join both (raw + details) in the same page.~~
- [x] In the Transaction list, Proposer is not correct, the shown value is Hash
- [x] Show tx summary info on details page (such tx number)
- [x] https://github.com/vocdoni/explorer/pull/99 This may not be needed if below issue is implemented

**Comment by p4u** [comment]
Some of these changes also require backend changes.

**Comment by elboletaire** [comment]
> On transactions details, show only the RAW content of tx and signature, not txInfo. Since txInfo is already shown in Details tab. Maybe join both (raw + details) in the same page.

I do not agree with this one. The RAW content should show everything. Also, some information from txinfo may be missed in the details section. Still, even though everything was there, the raw content should show everything.
