### ISSUE TITLE
Links visibility

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/explorer#69]
Links should be visible (different color and underline).

For instance, the "process id" is a link but seems plain text:
![image](https://github.com/user-attachments/assets/9d0ae0f7-db8f-4e5a-a23f-fddc641f1b4a)

or the "View Profile" link as well. 

Don't do it in the navigation links (i.e: the header links).

**Comment by elboletaire** [comment]
We should standarize the way we're showing them... i.e. there are lots of green links, maybe we should make that the default for all links.
